DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;
DROP TABLE IF EXISTS orders CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone INTEGER NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  profile_img_url VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  time_placed TIMESTAMP,
  is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
  aprox_time INTEGER,
  total_price INTEGER NOT NULL DEFAULT 0.00
  notes VARCHAR(255),
  restaurant_id INTEGER REFERENCES restaurants(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
);
