DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone INTEGER NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  profile_img_url VARCHAR(255) NOT NULL,
  owner INTEGER REFERENCES users(id) ON DELETE CASCADE,
);
